In [4]:

import sys

print("Python utilisé :", sys.executable)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pathlib import Path

print("NumPy :", np.__version__)
print("Pandas :", pd.__version__)
print("Matplotlib :", plt.matplotlib.__version__)

print("Tout fonctionne !")

Python utilisé : c:\Users\PC\Desktop\HETIC\spotify-analysis-2026\.venv\Scripts\python.exe
NumPy : 1.26.4
Pandas : 2.2.3
Matplotlib : 3.8.4
Tout fonctionne !

In [5]:
import sys

print("Python utilisé par le notebook :")
print(sys.executable)

Python utilisé par le notebook :
c:\Users\PC\Desktop\HETIC\spotify-analysis-2026\.venv\Scripts\python.exe

In [6]:
DATA_PATH = Path("../data/raw/spotify-albums_data_2023.csv")
df = pd.read_csv(DATA_PATH, low_memory=False)

print("Dataset charger avec sucees !!")
print("dimension : " , df.shape )

Dataset charger avec sucees !!
dimension :  (438973, 26)

In [7]:
print("nombre de ligne " , df.shape[0])
print("nombre des colonnes : " , df.shape[1])

display(df.head())

nombre de ligne  438973
nombre des colonnes :  26

,track_name,track_id,track_number,duration_ms,album_type,artists,total_tracks,album_name,release_date,label,...,artist_3,artist_4,artist_5,artist_6,artist_7,artist_8,artist_9,artist_10,artist_11,duration_sec
0,Amazing Grace,6mN8nzCXWUeT5LWEcG1Utx,5,555521,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,555.521
1,Silent Night,58sgjtx3FOnBBEOd3BQE6C,8,535041,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,535.041
2,Ancient Canyons,45tQJhm0WSk5VWMZK3FsLK,1,545855,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.855
3,Pacha Mama Medicina,3VFD7QqkJSg0OR6yBwKl7A,6,305241,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.241
4,Palace Of Light,7LwJV5BEIC9BQnzvaBSyCc,7,351060,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.060

In [8]:

print("Liste des colonnes :")
for colonne in df.columns:
    print("-", colonne)

Liste des colonnes :
- track_name
- track_id
- track_number
- duration_ms
- album_type
- artists
- total_tracks
- album_name
- release_date
- label
- album_popularity
- album_id
- artist_id
- artist_0
- artist_1
- artist_2
- artist_3
- artist_4
- artist_5
- artist_6
- artist_7
- artist_8
- artist_9
- artist_10
- artist_11
- duration_sec

In [9]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438973 entries, 0 to 438972
Data columns (total 26 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   track_name        438968 non-null  object
 1   track_id          438973 non-null  object
 2   track_number      438973 non-null  int64
 3   duration_ms       438973 non-null  int64
 4   album_type        438973 non-null  object
 5   artists           0 non-null       float64
 6   total_tracks      438973 non-null  int64
 7   album_name        438972 non-null  object
 8   release_date      438950 non-null  object
 9   label             438921 non-null  object
 10  album_popularity  438973 non-null  int64
 11  album_id          438973 non-null  object
 12  artist_id         438973 non-null  object
 13  artist_0          438970 non-null  object
 14  artist_1          100485 non-null  object
 15  artist_2          43650 non-null   object
 16  artist_3          16362 non-null   object
 17  artist_4          7173 non-null    object
 18  artist_5          3945 non-null    object
 19  artist_6          2549 non-null    object
 20  artist_7          0 non-null       float64
 21  artist_8          0 non-null       float64
 22  artist_9          0 non-null       float64
 23  artist_10         0 non-null       float64
 24  artist_11         0 non-null       float64
 25  duration_sec      438973 non-null  float64
dtypes: float64(7), int64(4), object(15)
memory usage: 87.1+ MB

In [10]:
display(df.describe(include="all").T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
track_name,438968,301279,Intro,553,NaN,NaN,NaN,NaN,NaN,NaN,NaN
track_id,438973,438948,0y24jS32Msz0vmm8i9i8ZH,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN
track_number,438973.0,NaN,NaN,NaN,8.367467,8.391625,1.0,2.0,6.0,11.0,110.0
duration_ms,438973.0,NaN,NaN,NaN,216269.370604,127867.003321,0.0,160719.0,205295.0,251933.0,17919000.0
album_type,438973,3,album,307750,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artists,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
total_tracks,438973.0,NaN,NaN,NaN,19.168142,26.403792,1.0,9.0,13.0,21.0,984.0
album_name,438972,63485,Nirvana,988,NaN,NaN,NaN,NaN,NaN,NaN,NaN
release_date,438950,7731,2008-01-01 00:00:00 UTC,2439,NaN,NaN,NaN,NaN,NaN,NaN,NaN
label,438921,34933,CC Entertainment,5654,NaN,NaN,NaN,NaN,NaN,NaN,NaN
album_popularity,438973.0,NaN,NaN,NaN,17.512667,20.620725,0.0,1.0,8.0,29.0,100.0
album_id,438973,78172,2J2XOIDnJSyNko5Vc4GII5,50,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_id,438973,37012,0LyfQWJT6nXafLPZqxe9Of,25734,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_0,438970,51946,Johann Sebastian Bach,3109,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_1,100485,29487,Sound Healing Center,1450,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_2,43650,11304,Sound Healing Center,1300,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_3,16362,4565,George Guest,255,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_4,7173,2100,James Bowman,96,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_5,3945,1046,James Taylor,90,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_6,2549,623,Andreas Schmidt,91,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_7,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_8,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_9,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_10,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
artist_11,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
duration_sec,438973.0,NaN,NaN,NaN,216.269371,127.867003,0.0,160.719,205.295,251.933,17919.0

In [11]:

manquants = pd.DataFrame({
    "nombre_manquant": df.isna().sum(),
    "pourcentage_manquant": (df.isna().mean() * 100).round(2)
})

manquants = manquants.sort_values(
    "pourcentage_manquant",
    ascending=False
)

display(manquants[manquants["nombre_manquant"] > 0])

              nombre_manquant  pourcentage_manquant
artist_11              438973                100.00
artist_10              438973                100.00
artist_9               438973                100.00
artists                438973                100.00
artist_8               438973                100.00
artist_7               438973                100.00
artist_6               436424                 99.42
artist_5               435028                 99.10
artist_4               431800                 98.37
artist_3               422611                 96.27
artist_2               395323                 90.06
artist_1               338488                 77.11
release_date               23                  0.01
label                      52                  0.01
track_name                  5                  0.00
artist_0                    3                  0.00
album_name                  1                  0.00

In [12]:
nb_doublons = df.duplicated().sum()

print(" nombre de ligne dupliquee : " , nb_doublons)
print("pourcentage de doublons : " , round(nb_doublons / len(df)* 100 , 2),  "%")

 nombre de ligne dupliquee :  0
pourcentage de doublons :  0.0 %

In [13]:

if "album_type" in df.columns:
    print("Nombre d'albums par type :")
    display(df["album_type"].value_counts(dropna=False))

    print("\nRépartition en pourcentage :")
    display(
        (df["album_type"].value_counts(
            normalize=True, dropna=False
        ) * 100).round(2)
    )
else:
    print("La colonne album_type n'existe pas.")

Nombre d'albums par type :

album_type
album          307750
single          86754
compilation     44469
Name: count, dtype: int64

Répartition en pourcentage :

album_type
album          70.11
single         19.76
compilation    10.13
Name: proportion, dtype: float64

In [14]:

if "release_date" in df.columns:
    dates = pd.to_datetime(df["release_date"], errors="coerce")

    print("Dates non interprétables :", dates.isna().sum())
    print("Date la plus ancienne :", dates.min())
    print("Date la plus récente :", dates.max())
else:
    print("La colonne release_date n'existe pas.")

Dates non interprétables : 23
Date la plus ancienne : 1886-01-01 00:00:00+00:00
Date la plus récente : 2023-12-22 00:00:00+00:00

In [15]:

dates = pd.to_datetime(df["release_date"], errors="coerce")

print("Nombre de dates invalides ou manquantes :", dates.isna().sum())
print("Date la plus ancienne :", dates.min())
print("Date la plus récente :", dates.max())

print("\nExemples de dates originales :")
display(df["release_date"].dropna().head(10))

Nombre de dates invalides ou manquantes : 23
Date la plus ancienne : 1886-01-01 00:00:00+00:00
Date la plus récente : 2023-12-22 00:00:00+00:00

Exemples de dates originales :

0    2015-06-09 00:00:00 UTC
1    2015-06-09 00:00:00 UTC
2    2015-06-09 00:00:00 UTC
3    2015-06-09 00:00:00 UTC
4    2015-06-09 00:00:00 UTC
5    2015-06-09 00:00:00 UTC
6    2015-06-09 00:00:00 UTC
7    2015-06-09 00:00:00 UTC
8    2015-06-09 00:00:00 UTC
9    2019-12-20 00:00:00 UTC
Name: release_date, dtype: object

In [ ]:

df_dates = df.copy()
df_dates["release_date_convertie"] = pd.to_datetime(
    df_dates["release_date"], errors="coerce", utc=True
)

display(
    df_dates.loc[
        df_dates["release_date_convertie"].dt.year < 1950,
        ["album_name", "track_name", "release_date", "album_type"]
    ].sort_values("release_date").head(20)
)

,album_name,track_name,release_date,album_type
107873,Electronic Satie - Ogives,Deuxième Ogive,1886-01-01 00:00:00 UTC,single
107870,Electronic Satie - Ogives,Quatrième Ogive,1886-01-01 00:00:00 UTC,single
107871,Electronic Satie - Ogives,Troisième Ogive,1886-01-01 00:00:00 UTC,single
107872,Electronic Satie - Ogives,Première Ogive,1886-01-01 00:00:00 UTC,single
112888,'A Figlia D'À Madonna,E' Fantastica,1899-12-30 00:00:00 UTC,album
112887,'A Figlia D'À Madonna,Serenata A 'Nzuccarata,1899-12-30 00:00:00 UTC,album
112886,'A Figlia D'À Madonna,Impronta Digitale,1899-12-30 00:00:00 UTC,album
112885,'A Figlia D'À Madonna,Che Femmena Si Tu,1899-12-30 00:00:00 UTC,album
112883,'A Figlia D'À Madonna,Fore 'A Chiesa,1899-12-30 00:00:00 UTC,album
112882,'A Figlia D'À Madonna,'A Figlia D'A Madonna,1899-12-30 00:00:00 UTC,album
123409,Madonna: Basi Musicali,Take A Bow - Instrumental,1899-12-30 00:00:00 UTC,album
123402,Madonna: Basi Musicali,Like A Virgin - Only Base,1899-12-30 00:00:00 UTC,album
123410,Madonna: Basi Musicali,The Power Of Goodbye - Only Base,1899-12-30 00:00:00 UTC,album
123411,Madonna: Basi Musicali,La Isla Bonita - Instrumental,1899-12-30 00:00:00 UTC,album
123412,Madonna: Basi Musicali,La Isla Bonita - Only Base,1899-12-30 00:00:00 UTC,album
123413,Madonna: Basi Musicali,Take A Bow - Only Base,1899-12-30 00:00:00 UTC,album
112881,'A Figlia D'À Madonna,Nun E' Natale,1899-12-30 00:00:00 UTC,album
123403,Madonna: Basi Musicali,Don'T Cry For Me Argentina - Instrumental,1899-12-30 00:00:00 UTC,album
112884,'A Figlia D'À Madonna,'O Vesuvio Cu Tte,1899-12-30 00:00:00 UTC,album
123405,Madonna: Basi Musicali,Hollywood - Only Base,1899-12-30 00:00:00 UTC,album



# Premières observations

 **Dimensions du dataset :** 438 973 lignes et 26 colonnes.

 **Colonnes présentant le plus de valeurs manquantes :**
  `artists`, `artist_7`, `artist_8`, `artist_9`, `artist_10` et `artist_11` contiennent 100 % de valeurs manquantes. Les colonnes `artist_6`, `artist_5`, `artist_4`, `artist_3`, `artist_2` et `artist_1` présentent également un taux élevé de valeurs manquantes.

**Nombre de lignes dupliquées :** 0 doublon détecté, soit 0 % des lignes.

 **Type d'album le plus fréquent :** `album`, avec 307 750 lignes (70,11 %), suivi de `single` avec 86 754 lignes (19,76 %) et de `compilation` avec 44 469 lignes (10,13 %).

**Période couverte par les dates de sortie :** du 1er     janvier 1886 au 22 décembre 2023. La colonne `release_date` comporte 23 dates manquantes ou non interprétables.

**Points à vérifier avant le nettoyage :**
 Examiner les colonnes d'artistes très incomplètes et déterminer lesquelles sont utiles.
 Vérifier les dates anciennes, notamment celles antérieures à l'existence de l'industrie musicale enregistrée telle qu'on la connaît aujourd'hui.
 Décider comment traiter les 23 dates manquantes.
 Examiner les 52 valeurs manquantes de `label`, les 5 de `track_name`, la valeur manquante de `album_name` et les 3 de `artist_0`.
  Contrôler les valeurs aberrantes dans les variables numériques.